package scripture

import "github.com/mahesh-hegde/dhee/app/common"

type Modifier string

type ExcerptGlossing struct {
	Surface      string     `json:"surface"`
	Lemma        string     `json:"lemma"`
	Gramm        string     `json:"gramm"`
	Case         string     `json:"case,omitempty"`
	Number       string     `json:"number,omitempty"`
	Gender       string     `json:"gender,omitempty"`
	Tense        string     `json:"tense,omitempty"`
	Voice        string     `json:"voice,omitempty"`
	Person       string     `json:"person,omitempty"`
	Mood         string     `json:"mood,omitempty"`
	Root         string     `json:"root,omitempty"`
	Modifiers    []Modifier `json:"modifiers,omitempty"`
	Constituents []string   `json:"constituents,omitempty"`
}

type Auxiliary struct {
	Text []string `json:"text"`
}

type ExternalLink struct {
	Url  string `json:"url"`
	Name string `json:"name"`
}

type Related struct {
	SourceName              string   `json:"source_name"`
	Path                    []int    `json:"path"`
	EmbeddingRelevanceScore *float32 `json:"embedding_relevance_score,omitempty"`
	TextualRelevanceScore   *float32 `json:"textual_relevance_score,omitempty"`
	AutoGenerated           bool     `json:"auto_generated"`
}

type SearchParams struct {
	// name of scriptures to search
	Scriptures []string
	Mode       common.SearchMode
	Q          string
	Tl         string
	// Name of auxiliary, or "0" for sanskrit text, or "1" for roman text. Empty implies all auxiliaries, roman and source text
	SearchIn []string
}

// Excerpt represents a single atomic unit from the source text. Eg: a Rik in case of Rigveda.
type Excerpt struct {
	// Not serialized to JSON, but computed based on which file we are reading and stored in DB
	Scripture string `json:"scripture,omitempty"`
	// Eg: "4.30.1". Autocomputed from path if does not exist.
	ReadableIndex string `json:"readable_index"`
	// Hierarchical path in the document. Eg: mandala 4 hymn 30 verse 1 will be [4,30,1].
	Path []int `json:"path"`
	// Source text in original language
	SourceText []string `json:"source_text"`
	// Romanized text (eg: IAST)
	RomanText []string `json:"roman_text"`
	// Authors to whom the verse is attributed
	Authors []string `json:"authors,omitempty"`
	Meter   string   `json:"meter,omitempty"`
	// Complex type. 2D array with each row corresponding to one division of the verse.
	Glossings [][]ExcerptGlossing `json:"glossings,omitempty"`
	// Translations and alternative renderings
	Auxiliaries   map[string]Auxiliary `json:"auxiliaries,omitempty"`
	Notes         []string             `json:"notes,omitempty"`
	Links         []ExternalLink       `json:"links,omitempty"`
	Suggested     []Related            `json:"suggested,omitempty"`
	SuggestedAuto []Related            `json:"suggested_auto,omitempty"`
}

type HighlightedExcerpt struct {
	Excerpt     Excerpt
	SourceHl    string // Highlighted source text
	RomanHl     string // Highlighted roman text, and so on
	AuxiliaryHl map[string]Auxiliary
	NotesHl     []string
}

// Type implements mapping.Classifier.
func (e *Excerpt) Type() string {
	return "excerpt"
}

type QualifiedPath struct {
	Scripture string // Name of the scripture
	Path      []int  // Hierarchical path
}
