package textbrowser

type AuxiliaryDefinition struct {
	Name         string
	ReadableName string
	Language     string
}

type SourceDefinition struct {
	Name         string
	ReadableName string
	Description  string
	Collector    string
	Hierarchy    []string
	Auxiliaries  []AuxiliaryDefinition
}

type Modifier string

// ExcerptGlossing represents the grammatic derivation information of a single
// word.
type ExcerptGlossing struct {
	Word         string
	Root         string
	Modifiers    []Modifier
	Constituents []string
	// IDs to find this word in various dictionaries
	DictionaryIDs map[string]string
}

type Auxiliary struct {
	Path []int
	Text []string
}

type ExternalLink struct {
	Url  string
	Name string
}

type Related struct {
	SourceName              string
	Path                    []int
	EmbeddingRelevanceScore *float32
	TextualRelevanceScore   *float32
	AutoGenerated           bool
}

// Excerpt represents smallest atomic excerpt of a given text, as defined by
// the last element of the hierarchy in SourceDefinition.
//
// For example, with Rigveda, one excerpt corresponds to one Rik.
type Excerpt struct {
	// Optional index eg: "4.30.1". If not provided, its constructed from Path
	ReadableIndex string
	// Path in the hierarchy of source text. Eg: [4,30,1]
	Path          []int
	Text          []string // One element per line of displayed text.
	Authors       []string
	Meter         string
	Glossings     [][]ExcerptGlossing
	Auxiliaries   []Auxiliary
	Notes         []string // Notes by the curator
	Links         []ExternalLink
	Suggested     []Related // Suggestions on related excerpts in same or different source text
	SuggestedAuto []Related // Suggestions on related excerpts in same or different source text
}

// This is never needed since we query from a text storage engine?
type SourceData struct {
	Excerpts []Excerpt
}
