package textbrowser

type AuxiliaryDefinition struct {
	Name         string
	ReadableName string
	Language     string
}

type SourceDefinition struct {
	Name         string
	ReadableName string
	Description  string
	Collector    string
	Hierarchy    []string
	Auxiliaries  []AuxiliaryDefinition
}

type Modifier string

type ExcerptGlossing struct {
	Surface      string     `json:"surface"`
	Lemma        string     `json:"lemma"`
	Gramm        string     `json:"gramm"`
	Case         string     `json:"case,omitempty"`
	Number       string     `json:"number,omitempty"`
	Gender       string     `json:"gender,omitempty"`
	Tense        string     `json:"tense,omitempty"`
	Voice        string     `json:"voice,omitempty"`
	Person       string     `json:"person,omitempty"`
	Mood         string     `json:"mood,omitempty"`
	Root         string     `json:"root,omitempty"`
	Modifiers    []Modifier `json:"modifiers,omitempty"`
	Constituents []string   `json:"constituents,omitempty"`
}

type Auxiliary struct {
	Path []int    `json:"path"`
	Text []string `json:"text"`
}

type ExternalLink struct {
	Url  string `json:"url"`
	Name string `json:"name"`
}

type Related struct {
	SourceName              string   `json:"source_name"`
	Path                    []int    `json:"path"`
	EmbeddingRelevanceScore *float32 `json:"embedding_relevance_score,omitempty"`
	TextualRelevanceScore   *float32 `json:"textual_relevance_score,omitempty"`
	AutoGenerated           bool     `json:"auto_generated"`
}

type Excerpt struct {
	ReadableIndex string               `json:"readable_index"`
	Path          []int                `json:"path"`
	SourceText    []string             `json:"source_text"`
	RomanText     []string             `json:"roman_text"`
	Authors       []string             `json:"authors,omitempty"`
	Meter         string               `json:"meter,omitempty"`
	Glossings     [][]ExcerptGlossing  `json:"glossings,omitempty"`
	Auxiliaries   map[string]Auxiliary `json:"auxiliaries,omitempty"`
	Notes         []string             `json:"notes,omitempty"`
	Links         []ExternalLink       `json:"links,omitempty"`
	Suggested     []Related            `json:"suggested,omitempty"`
	SuggestedAuto []Related            `json:"suggested_auto,omitempty"`
}

// This is never needed since we query from a text storage engine?
type SourceData struct {
	Excerpts []Excerpt
}
