// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package templ_template

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func CssTooltip(helpText string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<style>\n\t\t.css-tooltip-container {\n\t\t\tposition: relative;\n\t\t\tdisplay: inline-flex;\n\t\t\talign-items: center;\n\t\t}\n\t\t.css-tooltip-text {\n\t\t\tvisibility: hidden;\n\t\t\topacity: 0;\n\t\t\ttransition: opacity 0.15s linear;\n\t\t\tmin-width: 350px;\n\t\t\tbackground-color: #212529;\n\t\t\tcolor: #fff;\n\t\t\ttext-align: left;\n\t\t\tborder-radius: 0.375rem;\n\t\t\tpadding: 0.5rem 1rem;\n\t\t\tposition: absolute;\n\t\t\tz-index: 1080;\n\t\t\tbottom: 125%;\n\t\t\tleft: 50%;\n\t\t\ttransform: translateX(-50%);\n\t\t}\n\t\t.css-tooltip-text ul {\n\t\t\tpadding-left: 1.2rem;\n\t\t\tmargin-bottom: 0;\n\t\t}\n\t\t.css-tooltip-container:hover .css-tooltip-text {\n\t\t\tvisibility: visible;\n\t\t\topacity: 0.9;\n\t\t}\n\t\t.css-tooltip-text::after {\n\t\t\tcontent: \"\";\n\t\t\tposition: absolute;\n\t\t\ttop: 100%;\n\t\t\tleft: 50%;\n\t\t\tmargin-left: -5px;\n\t\t\tborder-width: 5px;\n\t\t\tborder-style: solid;\n\t\t\tborder-color: #212529 transparent transparent transparent;\n\t\t}\n\t</style><div class=\"css-tooltip-container\"><span class=\"badge rounded-pill bg-secondary\" style=\"cursor: help;\">?</span><div class=\"css-tooltip-text\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.Raw(helpText).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
