name: default-pipeline
on:
  push:
    tags:
      - v*

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  pre-build-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c
        with:
          go-version: "^1.24.2"
      - name: Install gofumpt
        run: go install mvdan.cc/gofumpt@e350b3cdcd03387e0e77f9fd637c27a6d30e1a3f
      - name: Check for compilation errors
        run: go build ./cmd/dhee
      - name: Check formatting
        run: gofumpt -w -l . && git diff --exit-code
      - name: Run tests
        run: go test ./...
  build-docker-image:
    runs-on: ubuntu-latest
    needs: [pre-build-checks]
    env:
      TAG_NAME: ${{ github.ref_name }}
      IMAGE_NAME: ghcr.io/mahesh-hegde/dhee
      IMAGE_NAME_ECR: ${{ vars.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
      - name: Docker login
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      # Build and push server image
      - name: Docker build (server)
        run: docker build -t "${IMAGE_NAME}:latest" --platform linux/amd64 -f Dockerfile .
      - name: Push server latest image
        run: docker push $IMAGE_NAME:latest
      - name: Tag server image
        run: docker tag $IMAGE_NAME:latest $IMAGE_NAME:${TAG_NAME#v}
      - name: Push server tagged image
        run: docker push $IMAGE_NAME:${TAG_NAME#v}
      
      # Build and push Lambda image to ECR
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@e7f100cf4c008499ea8adda475de1042d6975c7b
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: dhee-push
          aws-region: ${{ vars.AWS_REGION }}
      - name: Docker build (lambda)
        run: docker build -t "${IMAGE_NAME_ECR}:current" --platform linux/amd64 -f Dockerfile.lambda .
      - name: List image with size
        run: docker images | grep "${IMAGE_NAME_ECR}"
      - name: login to ECR
        run: aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin ${{ vars.ECR_REGISTRY }}
      - name: Push lambda tagged image
        run: docker push $IMAGE_NAME_ECR:current
